apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-access-view
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups:
      - access.strimzi.io
    resources:
      - kafkaaccesses
      - kafkaaccesses/status
    verbs:
      - get
      - watch
      - list