apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: kafka-service
spec:
  workload:  
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-deployment
  service:
    apiVersion: access.strimzi.io/v1alpha1
    kind: KafkaAccess
    name: my-kafka-access
